name: lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip
      - run: pip install wheel==0.42.0
      - run: pip install -r requirements.txt
      - run: pylint $(find -name *.py -not -path "./.venv/*")
      - run: flake8
      - run: make clean-release copy license VERSION=0.0.0
      - run: kodi-addon-checker --branch  matrix release/plugin.video.crunchyreroll
